{"uuid":"074494b8-1208-46ca-b067-dc79e96213bb","historyId":"8d5926ac792514b6da436c594503f7a4","fullName":"com.autotest.testcase.unittest.AddUserApiTest.adduser","labels":[{"name":"package","value":"com.autotest.testcase.unittest.AddUserApiTest"},{"name":"testClass","value":"com.autotest.testcase.unittest.AddUserApiTest"},{"name":"testMethod","value":"adduser"},{"name":"parentSuite","value":"apiAutoTest"},{"name":"suite","value":"test"},{"name":"subSuite","value":"com.autotest.testcase.unittest.AddUserApiTest"},{"name":"host","value":"xiaohe0128"},{"name":"thread","value":"27788@xiaohe0128.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"story","value":"正反用例"},{"name":"feature","value":"添加用户接口"},{"name":"epic","value":"接口单元测试"}],"links":[],"name":"adduser","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"java.lang.reflect.InvocationTargetException","trace":"java.lang.reflect.InvocationTargetException\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat com.autotest.testcase.unittest.AddUserApiTest.reflect(AddUserApiTest.java:29)\r\n\tat com.autotest.testcase.unittest.AddUserApiTest.adduser(AddUserApiTest.java:70)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\r\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)\r\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)\r\n\tat org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)\r\n\tat org.testng.internal.Invoker.invokeMethod(Invoker.java:645)\r\n\tat org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)\r\n\tat org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)\r\n\tat org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)\r\n\tat org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)\r\n\tat org.testng.TestRunner.privateRun(TestRunner.java:756)\r\n\tat org.testng.TestRunner.run(TestRunner.java:610)\r\n\tat org.testng.SuiteRunner.runTest(SuiteRunner.java:387)\r\n\tat org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:289)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1218)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1133)\r\n\tat org.testng.TestNG.run(TestNG.java:1104)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)\r\nCaused by: java.lang.Exception: Failed : HTTP error code : 400\r\n\tat com.autotest.utils.RequestMethod.Post(RequestMethod.java:107)\r\n\t... 30 more\r\n"},"stage":"finished","steps":[],"attachments":[{"name":"请求地址：","source":"312e00b4-cd84-48e4-9103-9a30fb76467b-attachment.txt","type":"text/plain"},{"name":"请求方法","source":"6c0beadb-2483-4dd4-aede-6b6ee508953e-attachment.txt","type":"text/plain"},{"name":"请求参数","source":"27934e0e-8853-487b-97a2-ab917345a2ed-attachment.txt","type":"text/plain"},{"name":"请求头:","source":"70d1d0ad-1c2f-4116-8969-c5a80fc57b8e-attachment.txt","type":"text/plain"}],"parameters":[{"name":"arg3","value":"1"},{"name":"arg2","value":"abc"},{"name":"arg4","value":"why"},{"name":"arg1","value":"><:"},{"name":"arg0","value":"xx"}],"start":1727181187738,"stop":1727181187752}